### ISSUE TITLE
Clock Millis Overflow in N1QL

### ISSUE THREAD

**Issue by bignolip** [couchbaselabs/query#11]
Hi,

I hope this is the correct place to put the following issue.  If not, please direct me to the correct venue.  Thanks!

I have been experimenting with N1QL and came across this issue while using the built-in "STR_TO_MILLIS" date function to compare a date value to the current time.  This seemed to work until the date being compared against exceeded a particular limit.  

It appears that the maximum date before overflow occurs is:  "2846-10-30T23:21:50.564Z", which evaluates to 9,223,372,036,854.  

That value is approximately 1,000,000 less than the maximum value of a 64-bit number...I suspect that is not a coincidence as there is conversion in the code between millis and nanos, which differ by a factor of 1,000,000.

I think that the relevant code that controls this is in:  https://github.com/couchbase/query/blob/master/expression/func_date.go

Is there another date function that can be supplied that doesn't use UnixNano?  

Note the following from the GO Language Specification

"UnixNano returns t as a Unix time, the number of nanoseconds elapsed since January 1, 1970 UTC. The result is undefined if the Unix time in nanoseconds cannot be represented by an int64. Note that this means the result of calling UnixNano on the zero Time is undefined."

Failing the modification of the current STR_TO_MILLIS function or the implementation of an alternative that would not exhibit this overflow (at dates in a reasonable time frame), are there any existing ways to get around this?

Thanks!

Best,
Perrin

**Comment by geraldss** [comment]
Hi,

In the ISO format below, you can compare date strings directly, without converting to millis. Would that work for you?

Thanks,
Gerald

**Comment by bignolip** [comment]
Yes, that works!  Thanks Gerald!
