### ISSUE TITLE
Result slow on n1ql

### ISSUE THREAD

**Issue by kivervinicius** [couchbaselabs/query#12]
In a bank of approximately 300,000 records, the query below:

```
SELECT count(usuario) FROM analytics where 
    datahora.entrada >= '2016-11-18T00:00:00.000Z' and 
    datahora.entrada <= '2016-11-18T99:99:99.999Z' limit 5000
```
Takes about 1 min, using n1ql would it be possible to optimize it using indices? I tried to do as below but it did not work
```
CREATE INDEX `ANALYTICS_datahora-entrada` ON `analytics`((`datahora`.`entrada`)) WHERE (`_type` = "analytics") USING GSI
```

**Comment by geraldss** [comment]
How about this query with your index.

SELECT count(usuario)

FROM analytics

where

```
datahora.entrada >= '2016-11-18T00:00:00.000Z' and
datahora.entrada <= '2016-11-18T99:99:99.999Z’ and
```

_type = ‘analytics'

limit 5000;

**Comment by MikeGoldsmith** [comment]
Hi @kivervinicius 

You could also try using STR_TO_MILLIS function to convert your string to a unix timestamp. Details of available functions are [here](http://developer.couchbase.com/documentation/server/current/n1ql/n1ql-language-reference/datefun.html).

The comparison you're doing in your query is doing an ordinal comparison between two string, not a real datetime diff.

**Comment by geraldss** [comment]
Hi @Mike,

The date comparison using IS0-8601 dates is valid. No need to convert to MILLIS.

**Comment by kivervinicius** [comment]
@geraldss  wow, very thanks for this fast response, not using _type my query spent 13136ms, but using _type will reduced to 442ms

I created the index without where and reduced the time to 230ms

**Comment by kivervinicius** [comment]
@MikeGoldsmith  using STR_TO_MILLIS dont work :(

**Comment by geraldss** [comment]
This should be even faster, if you are using Couchbase 4.5.1. Note that because you are doing a COUNT, the LIMIT is superfluous.

CREATE INDEX `ANALYTICS_datahora-entrada` ON `analytics`((`datahora`.`entrada`, usuario)) WHERE (`_type` = "analytics”);

SELECT count(usuario) FROM analytics

where _type = ‘analytics’ and
    datahora.entrada >= '2016-11-18T00:00:00.000Z' and
    datahora.entrada <= '2016-11-18T99:99:99.999Z' limit 5000;

**Comment by kivervinicius** [comment]
@geraldss  tnks for all
